UPDATE query_entity SET json = JSON_INSERT(json, '$.fullyQualifiedName', JSON_EXTRACT(json, '$.name')) WHERE JSON_EXTRACT(json, '$.fullyQualifiedName') IS NULL;
ALTER TABLE bot_entity  ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE chart_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE chart_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE chart_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE classification ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE storage_container_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE storage_container_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE storage_container_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE dashboard_data_model_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE dashboard_data_model_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE dashboard_data_model_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE dashboard_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE dashboard_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE dashboard_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE dashboard_service_entity ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE data_insight_chart DROP COLUMN fullyQualifiedName;
ALTER TABLE data_insight_chart ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE database_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE database_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE database_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE database_schema_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE database_schema_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE database_schema_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE dbservice_entity ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE event_subscription_entity ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE glossary_entity  ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE glossary_term_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE glossary_term_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE glossary_term_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE ingestion_pipeline_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE ingestion_pipeline_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE ingestion_pipeline_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE kpi_entity   ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE messaging_service_entity  ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE metadata_service_entity   ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE metric_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE metric_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE metric_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE ml_model_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE ml_model_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE ml_model_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE mlmodel_service_entity  ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE pipeline_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE pipeline_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE pipeline_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE pipeline_service_entity  ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE policy_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE policy_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE policy_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE query_entity  ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE report_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE report_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE report_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE role_entity   ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE storage_service_entity  ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE table_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE table_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE table_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE tag DROP COLUMN fullyQualifiedName;
ALTER TABLE tag ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE tag ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE team_entity ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE test_case DROP COLUMN fullyQualifiedName;
ALTER TABLE test_case ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE test_case ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE test_connection_definition ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE test_connection_definition ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE test_definition ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE test_suite   ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE topic_entity DROP COLUMN fullyQualifiedName;
ALTER TABLE topic_entity ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE topic_entity ADD COLUMN name VARCHAR(256) GENERATED ALWAYS AS (json_value(json , '$.name')) NOT NULL;
ALTER TABLE type_entity  ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE user_entity   ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE web_analytic_event DROP COLUMN fullyQualifiedName;
ALTER TABLE web_analytic_event ADD COLUMN fqnHash VARCHAR(768) NOT NULL;
ALTER TABLE automations_workflow  ADD COLUMN nameHash VARCHAR(256) NOT NULL;
ALTER TABLE field_relationship ADD COLUMN fromFQNHash VARCHAR(382);
ALTER TABLE field_relationship ADD COLUMN toFQNHash VARCHAR(382);
ALTER TABLE entity_extension_time_series ADD COLUMN entityFQNHash VARCHAR (768) NOT NULL;
ALTER TABLE tag_usage ADD COLUMN tagFQNHash VARCHAR(382);
ALTER TABLE tag_usage ADD COLUMN targetFQNHash VARCHAR(382);